
def get_data_names(data_schema):
    if data_schema == "qualifying_start":
        return ["rankGroup_local",
                "rankGroup_global",
                "teamGroup_team",
                "ratingGroup_rating",
                "highestGroup_rank_max",
                "highestGroup_rating_max",
                "averageGroup_rank_avg",
                "averageGroup_rating_avg",
                "lowestGroup_rank_min",
                "lowestGroup_rating_min",
                "change3mGroup_rank_three_month_change",
                "change3mGroup_rating_three_month_change",
                "change6mGroup_rank_six_month_change",
                "change6mGroup_rating_six_month_change",
                "change1yGroup_rank_one_year_change",
                "change1yGroup_rating_one_year_change",
                "change2yGroup_rank_two_year_change",
                "change2yGroup_rating_two_year_change",
                "change5yGroup_rank_five_year_change",
                "change5yGroup_rating_five_year_change",
                "change10yGroup_rank_ten_year_change",
                "change10yGroup_rating_ten_year_change",
                "matchesGroup_total",
                "matchesGroup_home",
                "matchesGroup_away",
                "matchesGroup_neutral",
                "matchesGroup_wins",
                "matchesGroup_losses",
                "matchesGroup_draws",
                "goalsGroup_for",
                "goalsGroup_against"]
    elif data_schema == "qualifying_results":
        return ["year", "month", "date",
                "team_1", "team_2",
                "score_team_1", "score_team_2",
                "tournament", "country_played", "rating_moved",
                "rating_team_1", "rating_team_2",
                "rank_moved_team_1", "rank_moved_team_2",
                "rank_team_1", "rank_team_2"]
